project:
  type: website
  output-dir: docs

# Meta
description-meta: "Jianing Ding's personal website"
author-meta: "Jianing Ding"

website:
  title: "Jianing Ding"
  image: "files/profiles/2024-06-03 204008.JPG"
  description: "Jianing Ding's personal website"
 
  navbar:
    background: light

    left:
#      - text: Home
#        href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Experiences
        href: projects.qmd                                
      - text: Posts
        href: posts.qmd  
      - text: Contact
        href: contact.qmd 

    right: 
      - text: CV
        href: files/CV-Jianing.pdf
      - icon: github
        href: https://github.com/jianing-d
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app
        target: _blank   
#      - text: '<i class="ai ai-google-scholar fa-lg"></i>'
#        href: https://scholar.google.com/citations?user=DY2D56IAAAAJ
  
  page-navigation: true
  
  page-footer: 
    center: "[Jianing Ding](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/jianing-d/jianingding.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://jianing-ding.netlify.app"
  
#  google-analytics:
#    tracking-id: ""  # Please delete or replace with your own tracking ID
#    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

